### PR TITLE
Updating example + adding new ones

### PR DESCRIPTION
**Pull request by tsurdilo**
The "helloworld" example that we have currently is incorrect and hard to understand.

 This updates it and makes it much more clearer and correct. It shows the data inputs and filter interactions etc. Also updates the example image.

This pr depends on https://github.com/cncf/wg-serverless/pull/124 which adds the workflow data input and output. 

You can see what this example looks like fully in my pr branch here: https://github.com/tsurdilo/wg-serverless/blob/examplesupdate1/workflow/spec/spec-examples.md

Also fixes the description of function parameters.

Also adds examples:
Looping state example
Parallel state example
Switch + SubFlow state example
Error Handling example

### CODE REVIEW

**Comment by salaboy** [comment]
/LGTM let's merge this one.. this example makes way much more sense.

**Comment by tsurdilo** [comment]
@salaboy thanks! we do have to add https://github.com/cncf/wg-serverless/pull/124 first tho hehe :)

**Comment by tsurdilo** [comment]
added looping example aswell

**Comment by tsurdilo** [comment]
added parallel example too

**Comment by tsurdilo** [comment]
@salaboy I added two more examples just fyi, if you can pls take a look again -- https://github.com/tsurdilo/wg-serverless/blob/examplesupdate1/workflow/spec/spec-examples.md

**Comment by tsurdilo** [comment]
added switch+subflow states examples

**Comment by tsurdilo** [comment]
added error handling example

**Comment by salaboy** [comment]
@tsurdilo examples make sense to me
/LGTM

**Pull request merged**
