### PR TITLE
Update WG non-goals

### PR DESCRIPTION
**Pull request by leecalcote**

### CODE REVIEW

**Comment by duglin** [comment]
LOL are you sure?

**Comment by duglin** [comment]
LGTM

**Comment by caniszczyk** [comment]
@leecalcote that was somewhat of a joke but just wanted to ensure all WGs list their "non-goals" :)

**Comment by leecalcote** [comment]
@caniszczyk got it. :) I realize the phrasing is somewhat comical, but also recognize the value in the public statement of this sentiment. Agree - that this concept is broad-sweeping across the WG's as a core ("no kingmakers") CNCF value.

**Comment by duglin** [comment]
Approved on 4/5 call

**Pull request merged**
