### PR TITLE
Update main readme

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@duglin could you please review as it updates the main wg readme. Thanks.

**Comment by tsurdilo** [comment]
@manuelstein so do you suggest we remove the:

World Time Zone Converter: https://www.thetimezoneconverter.com/?t=9%3A00%20am&tz=PT%20(Pacific%20Time)&

completely, replace it with something else or what?

**Comment by manuelstein** [comment]
Sorry, I don't recall what I was looking at when switched panes reviewing this.
I think world time zone converter is okay (accepting the risk of daylight saving time changes)

**Comment by duglin** [comment]
LGTM

**Pull request merged**
