### PR TITLE
Update workflow stream name

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@duglin would you mind taking a look please (as it changes the main readme file)

**Comment by duglin** [comment]
LGTM  as long as others in the workgroup at ok with it.... merge it!

**Comment by tsurdilo** [comment]
I'm not sure maybe ""Event Function Workflow" was the original name. All our docs mention "Serverless Workflow" specification. @cathyhongzhang - can you let us know?

**Comment by cathyhongzhang** [comment]
Serverless workflow looks good to me. Thanks.

**Pull request merged**
