### PR TITLE
formatting and json updates

### PR DESCRIPTION
**Pull request by tsurdilo**
* updated table of contents
* restructured doc to group things together little better
* fixed some wording
* updated anchor links

* updated json: changed all of the json examples to be actual json format. One change you might want to look at is that the name of states and triggers is no longer like:

```
"SOME-NAME": { ... } 
```

but a name field (which makes more sense for implementors):

```
{
   "name": "SOME-NAME",
   ...
}
```

### CODE REVIEW

**Comment by salaboy** [comment]
It looks good to me 👍

**Comment by ruromero** [comment]
I personally prefer this approach as it helps parsers and generators of any languages to parse this format. :+1:

**Comment by cathyhongzhang** [comment]
# @tsurdilo I like this change. Thank you!

**Comment by tsurdilo** [comment]
@cathyhongzhang thanks! I have some more coming ..but thought to start with a smaller one. You can see the JSON Schema we have created for the spac api project:

https://github.com/serverless-workflow/workflow-api
json schema: https://github.com/serverless-workflow/workflow-api/tree/master/src/main/resources/schema/workflow-01


and look at many tests to get some idea of what we have done. Our additions to the spec are not invasive at all, just make the implementations alot easier (and I'm sure there can be much more added to make it better!)

Btw. Can we talk about what we have done so far? Setting up some meet would be really nice if possible.

**Comment by tsurdilo** [comment]
@cathyhongzhang and others that have push rights -- can this be merged?

**Comment by cathyhongzhang** [comment]
I will ask Doug to merge this.

**Pull request merged**
