### PR TITLE
Avoiding Second Person use in spec docs

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by lucperkins** [comment]
As a professional technical writer, I strongly disagree with the principle behind most of these changes, even in a spec. Eliminating “you” in favor of passive voice makes sentences more abstract and distanced without any clear benefit to the reader.

**Comment by tsurdilo** [comment]
@lucperkins thanks for review! Yes I agree with you as in the original writing I tried to make it more engaging to the readers. The request for this came via a suggestion in a different pr to look at https://semo.edu/pdf/Writing_handout_Avoiding_Second_Person.pdf and use those practices.

I think it's best to close this PR. 

Would you be willing to help us with your expertise to improve the specification document writeup? This would be **huge** help to have and much much appreciated!

**Comment by tsurdilo** [comment]
Closing this pr after @lucperkins comments. 
@lucperkins It would be great if you could provide some help with the spec documents if you are interested. Thanks again.

**Comment by lucperkins** [comment]
@tsurdilo Absolutely happy to help!

**Pull request closed without merging**
